### PR TITLE
Potenetial fix for a TabSubMenu/TabInteractivelist issue

### LINKED ISSUE #90: UIMenu item in TabInteractiveList does not unfocus when Q or E are used to swap tab

### PR DESCRIPTION
**Pull request by oliverpope03**
Fixes #90.

### CODE REVIEW

File: Source/PauseMenu/TabView.cs [hunk 1]
```diff
@@ -172,6 +172,8 @@ public void ProcessControls()
                     Tabs[Index].Active = false;
                     Tabs[Index].Focused = false;
                     Tabs[Index].Visible = false;
+                    if (Tabs[Index] is TabSubmenuItem)
+                        (Tabs[Index] as TabSubmenuItem).RefreshIndex();
```
Comment (alexguirre) [inline Source/PauseMenu/TabView.cs:176]: This can be done with a single type check:
```suggestion
                    if (Tabs[Index] is TabSubmenuItem submenuItem)
                        submenuItem.RefreshIndex();
```

File: Source/PauseMenu/TabView.cs [hunk 2]
```diff
@@ -187,6 +189,8 @@ public void ProcessControls()
...
```
Comment (alexguirre) [inline Source/PauseMenu/TabView.cs:193]:
```suggestion
                    if (Tabs[Index] is TabSubmenuItem submenuItem)
                        submenuItem.RefreshIndex();
```

**Comment by alexguirre** [comment]
Looks good, I don't really like making special cases for specific items but I doing it some other way would require some refactoring.

**Comment by oliverpope03** [comment]
Yeah thats why i suggested it, thank you for showing me that trick with the "is" thatll optimize alot of my code as well, i wasnt sure how you would sort it but it seemed like a submenu specfic bug

**Comment by alexguirre** [comment]
Probably making the `Focused` or `Visible` properties virtual and overriding them on `TabSubmenuItem` to unfocus its items. But yeah, not planning on refactoring pause menus much on 1.7.

Anyways, thanks for the pull request.
